START_COOLTIME: 8
WAITING_PLAYER_SECOND: 5
GAME_TIME: 15
GAME_RESET_TIME: 5
GAME_RESTART_TIME: 10
CLICK_MESSAGE:
  accept_yes: "수락버튼"
  accept_no: "거절버튼"
  retry_yes: "다시하기 수락버튼"
  retry_no: "다시하기 거절버튼"
BOSS_BAR_TIMER_TITLE: "%second% 초 남았습니다."