MATCH_INITIALIZED_SECOND: 5
MATCH_WAITING_SECOND: 5
MATCH_SECOND: 15
WAITING_FOR_LEFT_USER_SECOND: 5
CLICK_MESSAGE:
  ACCEPT_YES: "PVP 수락하기 버튼"
  ACCEPT_NO: "PVP 거절하기 버튼"
  REPLAY_YES: "재시작 수락하기 버튼"
  REPLAY_NO: "재시작 거절하기 버튼"